all: lama_planner

TARBALL=fast-downward-19.06.tar.gz
TARBALL_URL=http://www.fast-downward.org/Releases/19.06?action=AttachFile&do=get&target=fast-downward-19.06.tar.gz

lama_planner:
	wget "$(TARBALL_URL)" -O fast-downward-19.06.tar.gz
	tar sxvf $(TARBALL)
	[ -d fast-downward ] && rm -rf fast-downward || :
	mv fast-downward-19.06 fast-downward
	rm -f $(TARBALL)
	python fast-downward/build.py
